[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
#androidx-espresso = "3.7.0"
#androidx-testExt = "1.3.0"
#junit = "4.13.2"
androidx-lifecycle = "2.9.4"
composeHotReload = "1.0.0-beta08"
composeMultiplatform = "1.9.0"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
koin = "4.1.1"
koin-annotations = "2.1.0"
ksp = "2.2.20-2.0.3"
room = "2.8.1"
sqlite = "2.6.1"
datastore = "1.1.7"
kotlinx-datetime = "0.7.1"
material3-adaptive = "1.2.0-alpha06"
ktorfit = "2.6.4"
coil = "3.3.0"
mockk = "1.14.5"
kotestAssertionsCore = "6.0.3"
roboelectric = "4.16"
prettytime = "5.0.9.Final"
kermit = "2.0.8"
kmpnotifier = "1.6.0"
gms = "4.4.3"
uri = "0.0.21"
appUpdate = "2.1.0"
kmp-essentials = "2.6.5"
androidx-navigation-compose = "2.9.0"
#kotlinStdlib = "2.2.20"
#runner = "1.5.2"
#core = "1.5.0"
#junit = "1.3.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk-jvm = { module = "io.mockk:mockk", version.ref = "mockk" } # https://github.com/mockk/mockk/releases
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" } # https://github.com/mockk/mockk/releases
mockk-android-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" } # https://github.com/mockk/mockk/releases
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotestAssertionsCore" } # https://github.com/kotest/kotest/releases
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" } # https://github.com/robolectric/robolectric/releases
#kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
#junit = { module = "junit:junit", version.ref = "junit" }
#androidx-testExt-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" } # https://developer.android.com/jetpack/androidx/releases/activity
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" } # https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" } # https://developer.android.com/jetpack/androidx/releases/lifecycle
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" } # https://github.com/Kotlin/kotlinx.coroutines/releases
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" } # https://github.com/InsertKoinIO/koin/releases
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" } # https://github.com/InsertKoinIO/koin/releases
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" } # https://github.com/InsertKoinIO/koin/releases
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" } # https://github.com/InsertKoinIO/koin/releases
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" } # https://github.com/InsertKoinIO/koin/releases
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" } # https://developer.android.com/jetpack/androidx/releases/sqlite
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" } # https://developer.android.com/jetpack/androidx/releases/room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" } # https://developer.android.com/jetpack/androidx/releases/room
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" } # https://developer.android.com/jetpack/androidx/releases/datastore
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" } # https://github.com/Kotlin/kotlinx-datetime/releases
prettytime = { module = "org.ocpsoft.prettytime:prettytime", version.ref = "prettytime" } # https://github.com/ocpsoft/prettytime/tags
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" } # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" } # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" } # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" } # https://foso.github.io/Ktorfit/CHANGELOG/
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" } # https://github.com/coil-kt/coil/blob/main/CHANGELOG.md
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" } # https://github.com/coil-kt/coil/blob/main/CHANGELOG.md
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" } # https://github.com/coil-kt/coil/blob/main/CHANGELOG.md
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" } # https://github.com/touchlab/Kermit/blob/main/CHANGELOG.md
firebase-messaging = { module = "io.github.mirzemehdi:kmpnotifier", version.ref = "kmpnotifier" } # https://github.com/mirzemehdi/KMPNotifier/releases
uri = { module = "com.eygraber:uri-kmp", version.ref = "uri" } # https://github.com/eygraber/uri-kmp/releases
app-update = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" } # https://developer.android.com/reference/com/google/android/play/core/release-notes-in_app_updates
kmp-essentials = { module = "io.github.thearchitect123:kmpEssentials", version.ref = "kmp-essentials" } # https://github.com/Ares-Defence-Labs/KmpEssentials/commits/main/
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" } # https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose-190.html
#kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
#androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
#androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" } # https://developer.android.com/build/releases/past-releases
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" } # https://github.com/JetBrains/compose-hot-reload/releases
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" } # https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose-190.html
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" } # https://kotlinlang.org/docs/whatsnew2020.html
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" } # https://kotlinlang.org/docs/whatsnew2020.html
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # https://github.com/google/ksp/releases
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" } # https://foso.github.io/Ktorfit/CHANGELOG/
androidx-room = { id = "androidx.room", version.ref = "room" } # https://developer.android.com/jetpack/androidx/releases/room
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" } # https://kotlinlang.org/docs/whatsnew2020.html
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" } # https://developer.android.com/build/releases/past-releases
android-lint = { id = "com.android.lint", version.ref = "agp" } # https://developer.android.com/build/releases/past-releases
google-services = { id = "com.google.gms.google-services", version.ref = "gms" } # https://firebase.google.com/support/release-notes/android
