[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
#androidx-core = "1.17.0"
#androidx-espresso = "3.7.0"
#androidx-testExt = "1.3.0"
#junit = "4.13.2"
androidx-lifecycle = "2.9.4"
composeHotReload = "1.0.0-beta08"
composeMultiplatform = "1.9.0"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
koin = "4.1.1"
koin-annotations = "2.1.0"
ksp = "2.2.20-2.0.3"
room = "2.8.1"
sqlite = "2.6.1"
datastore = "1.1.7"
kotlinx-datetime = "0.7.1"
material3-adaptive = "1.2.0-alpha06"
ktorfit = "2.6.4"
coil = "3.3.0"

[libraries]
#kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
#kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
#junit = { module = "junit:junit", version.ref = "junit" }
#androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
#androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
#androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" } # https://developer.android.com/jetpack/androidx/releases/activity
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" } # https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" } # https://developer.android.com/jetpack/androidx/releases/lifecycle
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" } # https://github.com/Kotlin/kotlinx.coroutines/releases
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" } # https://github.com/InsertKoinIO/koin/releases
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" } # https://github.com/InsertKoinIO/koin/releases
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" } # https://github.com/InsertKoinIO/koin/releases
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" } # https://github.com/InsertKoinIO/koin/releases
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" } # https://github.com/InsertKoinIO/koin/releases
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" } # https://developer.android.com/jetpack/androidx/releases/sqlite
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" } # https://developer.android.com/jetpack/androidx/releases/room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" } # https://developer.android.com/jetpack/androidx/releases/room
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" } # https://developer.android.com/jetpack/androidx/releases/datastore
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" } # https://github.com/Kotlin/kotlinx-datetime/releases
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" } # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" } # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" } # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" } # https://foso.github.io/Ktorfit/CHANGELOG/
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" } # https://github.com/coil-kt/coil/blob/main/CHANGELOG.md
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" } # https://github.com/coil-kt/coil/blob/main/CHANGELOG.md

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" } # https://developer.android.com/build/releases/past-releases
androidLibrary = { id = "com.android.library", version.ref = "agp" } # https://developer.android.com/build/releases/past-releases
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" } # https://github.com/JetBrains/compose-hot-reload/releases
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" } # https://github.com/JetBrains/compose-multiplatform/releases
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" } # https://kotlinlang.org/docs/whatsnew2020.html
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" } # https://kotlinlang.org/docs/whatsnew2020.html
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # https://github.com/google/ksp/releases
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" } # https://foso.github.io/Ktorfit/CHANGELOG/
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" } # https://kotlinlang.org/docs/whatsnew2020.html
