name: tests

env:
  USE_PROXY_REPO: false

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  components-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        cache-dependency-path: gradle/wrapper/gradle-wrapper.properties
    - run: ./gradlew :components:jvmTest
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Components
        path: components/build/test-results/jvmTest/**/TEST-*.xml
        reporter: java-junit
  jvm-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        cache-dependency-path: gradle/wrapper/gradle-wrapper.properties
    - run: ./gradlew :composeApp:jvmTest
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Components
        path: composeApp/build/test-results/jvmTest/**/TEST-*.xml
        reporter: java-junit
  android-tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo $ANDROID_HOME
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        cache-dependency-path: gradle/wrapper/gradle-wrapper.properties
    - run: ./gradlew :composeApp:testDebugUnitTest
    - name: Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Screenshots
        path: composeApp/build/outputs/roborazzi/*_compare.png
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Components
        path: composeApp/build/test-results/testDebugUnitTest/**/TEST-*.xml
        reporter: java-junit
